CREATE TABLE otp(
id SERIAL NOT NULL PRIMARY KEY,
email VARCHAR(255),
token INT,
purpose VARCHAR(255),
exp TIMESTAMP,
created_at TIMESTAMP  WITH TIME ZONE DEFAULT NOW() NOT NULL,
modified_at TIMESTAMP    
)