CREATE TABLE groupu(
id SERIAL NOT NULL PRIMARY KEY,
name VARCHAR(255),
pic_url VARCHAR(255),
description VARCHAR(255),
created_at TIMESTAMP  WITH TIME ZONE DEFAULT NOW() NOT NULL,
modified_at TIMESTAMP   
)

CREATE TABLE group_member(
id SERIAL NOT NULL PRIMARY KEY,
group_id INT,
username VARCHAR(255),
role VARCHAR(50),
created_at TIMESTAMP  WITH TIME ZONE DEFAULT NOW() NOT NULL
)